#!/bin/bash

cmd="killall java" 

ssh beet $cmd &    
ssh cabbage $cmd &
ssh carrot $cmd &   
ssh celery $cmd &
ssh fennel $cmd &
ssh mushroom $cmd &   
ssh lettuce $cmd & 
ssh parsley $cmd &
ssh pepper $cmd & 
ssh radish $cmd & 